// the values of this timings are contrived for testing.They do not necessarily reflect reality.
export const navigationAndResourceEntries = [
  {
    name: 'http://entry-one',
    toJSON: () => ({
      name: 'http://entry-one',
      entryType: 'navigation',
      startTime: 0,
      duration: 800,
      initiatorType: 'navigation',
      nextHopProtocol: 'http/1.1',
      workerStart: 0,
      redirectStart: 0,
      redirectEnd: 1,
      fetchStart: 1,
      domainLookupStart: 24,
      domainLookupEnd: 25,
      connectStart: 24,
      connectEnd: 25,
      secureConnectionStart: 0,
      requestStart: 25,
      responseStart: 35,
      responseEnd: 35,
      transferSize: 2800,
      encodedBodySize: 2815,
      decodedBodySize: 2825,
      serverTiming: [],
      unloadEventStart: 37,
      unloadEventEnd: 38,
      domInteractive: 60,
      domContentLoadedEventStart: 543,
      domContentLoadedEventEnd: 550,
      domComplete: 543,
      loadEventStart: 543,
      loadEventEnd: 560,
      type: 'reload',
      redirectCount: 0,
    }),
  },
  {
    name: 'http://entry-two',
    toJSON: () => ({
      name: 'http://entry-two',
      entryType: 'resource',
      startTime: 43,
      duration: 12,
      initiatorType: 'script',
      nextHopProtocol: 'http/1.1',
      workerStart: 0,
      redirectStart: 0,
      redirectEnd: 0,
      fetchStart: 43,
      domainLookupStart: 43,
      domainLookupEnd: 43,
      connectStart: 43,
      connectEnd: 43,
      secureConnectionStart: 0,
      requestStart: 53,
      responseStart: 55,
      responseEnd: 55,
      transferSize: 79270,
      encodedBodySize: 78982,
      decodedBodySize: 78982,
      serverTiming: [],
    }),
  },
  {
    name: 'http://entry-three',
    toJSON: () => ({
      name: 'http://entry-three',
      entryType: 'resource',
      startTime: 43,
      duration: 13,
      initiatorType: 'link',
      nextHopProtocol: 'http/1.1',
      workerStart: 0,
      redirectStart: 0,
      redirectEnd: 0,
      fetchStart: 43,
      domainLookupStart: 53,
      domainLookupEnd: 53,
      connectStart: 53,
      connectEnd: 53,
      secureConnectionStart: 0,
      requestStart: 53,
      responseStart: 56,
      responseEnd: 56,
      transferSize: 234008,
      encodedBodySize: 233732,
      decodedBodySize: 233732,
      serverTiming: [],
    }),
  },
] as const;

export const matchNavigationAndResourceEntriesTestResults = [
  {
    name: 'http://entry-one',
    entryType: 'navigation',
    startTime: '0',
    duration: '544',
    initiatorType: 'navigation',
    nextHopProtocol: 'http/1.1',
    workerStart: '0',
    redirectStart: '0',
    redirectEnd: '0',
    fetchStart: '1',
    domainLookupStart: '24',
    domainLookupEnd: '24',
    connectStart: '24',
    connectEnd: '24',
    secureConnectionStart: '0',
    requestStart: '25',
    responseStart: '35',
    responseEnd: '35',
    transferSize: '3039',
    encodedBodySize: '2819',
    decodedBodySize: '2819',
    serverTiming: '[]',
    unloadEventStart: '37',
    unloadEventEnd: '38',
    domInteractive: '60',
    domContentLoadedEventStart: '543',
    domContentLoadedEventEnd: '543',
    domComplete: '543',
    loadEventStart: '543',
    loadEventEnd: '544',
    type: 'reload',
    redirectCount: '0',
  },
  {
    name: 'http://entry-two',
    entryType: 'resource',
    startTime: '43',
    duration: '12',
    initiatorType: 'script',
    nextHopProtocol: 'http/1.1',
    workerStart: '0',
    redirectStart: '0',
    redirectEnd: '0',
    fetchStart: '43',
    domainLookupStart: '43',
    domainLookupEnd: '43',
    connectStart: '43',
    connectEnd: '43',
    secureConnectionStart: '0',
    requestStart: '53',
    responseStart: '55',
    responseEnd: '55',
    transferSize: '79270',
    encodedBodySize: '78982',
    decodedBodySize: '78982',
    serverTiming: '[]',
  },
  {
    name: 'http://entry-three',
    entryType: 'resource',
    startTime: '43',
    duration: '13',
    initiatorType: 'link',
    nextHopProtocol: 'http/1.1',
    workerStart: '0',
    redirectStart: '0',
    redirectEnd: '0',
    fetchStart: '43',
    domainLookupStart: '53',
    domainLookupEnd: '53',
    connectStart: '53',
    connectEnd: '53',
    secureConnectionStart: '0',
    requestStart: '53',
    responseStart: '56',
    responseEnd: '56',
    transferSize: '234008',
    encodedBodySize: '233732',
    decodedBodySize: '233732',
    serverTiming: '[]',
  },
];
