apiVersion: 1

deleteDatasources:
  - name: 'Mimir'
  - name: 'Tempo'
  - name: 'Loki'

datasources:
  - name: 'Mimir'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    url: 'http://${MIMIR_HOST}:${MIMIR_PORT}/prometheus'
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: 'mimir'
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: 'tempo'
          name: 'TraceID'

  - name: 'Tempo'
    type: 'tempo'
    access: 'proxy'
    orgId: 1
    url: 'http://${TEMPO_HOST}:${TEMPO_PORT}'
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: 'tempo'
    jsonData:
      lokiSearch:
        datasourceUid: 'loki'
      tracesToLogs:
        datasourceUid: 'loki'
      nodeGraph:
        enabled: 'true'
      serviceMap:
        datasourceUid: 'mimir'

  - name: 'Loki'
    type: 'loki'
    access: 'proxy'
    orgId: 1
    url: 'http://${LOKI_HOST}:${LOKI_PORT}'
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: 'loki'
    jsonData:
      derivedFields:
        - datasourceUid: 'tempo'
          matcherRegex: 'traceID=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'
