{
 "title": "Receiver",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_agent_receiver_logs_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Measurements",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_agent_receiver_measurements_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_agent_receiver_exceptions_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Exporter errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_agent_receiver_exporter_errors_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(app_agent_receiver_request_duration_seconds_count{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate Limited Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (increase(app_agent_receiver_request_duration_seconds_count{status=\"429\", instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(app_agent_receiver_request_duration_seconds_count{instance=\"$instance\", method=\"POST\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (instance) (increase(app_agent_receiver_request_duration_seconds_count{status=\"429\",instance=\"$instance\"}[5m]))",
     "legendFormat": "rate limited"
    },
    {
     "expr": "sum by(instance) (increase(app_agent_receiver_request_duration_seconds_count{status=~\"5.*\",instance=\"$instance\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Events ingested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(app_agent_receiver_logs_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "logs"
    },
    {
     "expr": "sum(increase(app_agent_receiver_exceptions_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "exceptions"
    },
    {
     "expr": "sum(increase(app_agent_receiver_measurements_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "measurements"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(app_agent_receiver_request_duration_seconds_sum{instance=\"$instance\"}[$__rate_interval]))) / (sum(rate(app_agent_receiver_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_agent_receiver_request_duration_seconds_bucket{instance=\"$instance\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Exporter errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(app_agent_receiver_exporter_errors_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "exporter errors"
    }
   ]
  }
 ]
}