---
name: test
kind: pipeline
type: docker

trigger:
  event:
    exclude:
      - push
      - tag
    include:
      - pull_request

steps:
  - name: install-dependencies
    image: node:lts-stretch
    commands:
      - yarn install --frozen-lockfile

  - name: build
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn build

  - name: lint
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn quality:lint

  - name: circular-dependencies-test
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn quality:circular-deps

  - name: unit-tests
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn quality:test

  - name: e2e-tests
    image: cypress/included:10.8.0
    depends_on:
      - install-dependencies
    commands:
      - yarn start:demo:prod
    environment:
      IS_TEST: 1

services:
  - name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

---
name: release
kind: pipeline
type: docker

trigger:
  event:
    exclude:
      - push
      - pull_request
    include:
      - tag

steps:
  - name: install-dependencies
    image: node:lts-stretch
    commands:
      - yarn install --frozen-lockfile

  - name: build
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn build

  - name: lint
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn quality:lint

  - name: circular-dependencies-test
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn quality:circular-deps

  - name: unit-tests
    image: node:lts-stretch
    depends_on:
      - install-dependencies
    commands:
      - yarn quality:test

  - name: e2e-tests
    image: cypress/included:10.8.0
    depends_on:
      - build
    commands:
      - yarn quality:e2e:ci
    environment:
      IS_TEST: 1

  - name: publish
    image: node:lts-stretch
    depends_on:
      - build
      - lint
      - circular-dependencies-test
      - unit-tests
      - e2e-tests
    commands:
      - git fetch --tags
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - yarn run publish from-git --yes --no-verify-access
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN

services:
  - name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

---
kind: signature
hmac: 8893b566b19aa834c1a354419bc9b320bf3ce4f39a1d34acb45a73631c98a153

...
