---
kind: pipeline
name: grafana-javascript-agent

steps:
  - name: Install dependencies
    image: node:lts-stretch
    commands:
      - yarn install --frozen-lockfile

  - name: Build
    image: node:lts-stretch
    commands:
      - yarn build

  - name: Lint
    image: node:lts-stretch
    commands:
      - yarn quality:lint

  - name: Check circular deps
    image: node:lts-stretch
    commands:
      - yarn quality:circular-deps

  - name: Unit tests
    image: node:lts-stretch
    commands:
      - yarn quality:test

  - name: End to end tests
    image: cypress/included:10.0.3
    commands:
      - cypress install
      - yarn quality:e2e:ci

  - name: Publish
    image: node:lts-stretch
    commands:
      - git fetch --tags
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - yarn run publish from-git --yes --no-verify-access
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    when:
      event:
        - tag
---
kind: signature
hmac: 0f74c578cb8e6fd32e68932f52565f71da663d7cf780fc28aa6ce361f6d60a6e

...
