name: 'Validate Semantic Pull Request'

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions: {}

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - id: lint-pr-title
        uses: grafana/shared-workflows/actions/lint-pr-title@e7a3275d4c4978a3514801ec55708f1c599a6906
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
