name: 'Validate Semantic Pull Request'

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions: {}

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - id: lint-pr-title
        uses: grafana/shared-workflows/actions/lint-pr-title@8b88213bca76e86f9f59b43038cc5d7545452436
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
