name: 'Validate Semantic Pull Request'

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions: {}

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - id: lint-pr-title
        uses: grafana/shared-workflows/actions/lint-pr-title@e776c0ba51ee2c8c97792e661ba8bd34c2642a55
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
